language: python
python:
  - 3.7
before_install:
  - python --version
  - python -m pip install pip
  - python -m pip install codecov
  - python -m pip install pytest
install:
  - python -m pip install -r requirements.txt
  - python setup.py develop
script: pytest
after_success:
  - codecov
